Update Partition3.java
Partition3.java:45: error: method partitionRecursion in class Partition3 cannot be applied to given types;
        System.out.println(partitionRecursion(A,0,0,0, totalSum));
                           ^
  required: int[],int,int,int,int,int
  found: int[],int,int,int,int
  reason: actual and formal argument lists differ in length
1 error